### ISSUE TITLE
Support Remote Images [@plaiceholder/next]

### ISSUE THREAD

**Issue by joe-bell** [joe-bell/plaiceholder#1]
**Is your feature request related to a problem? Please describe.**

Consumers of `next/image` who are using [Cloud Image Providers] would expect `next-blurhash` to provide the same support (not just local/public images)

**Describe the solution you'd like**

- **Caching** - Placeholders need to be generated at build time to be effective. Even with incremental static regeneration, there will be times when a consumer needs to rebuild an entire Next.js app. For thousands of images, this could make builds slow when fetching from a remote source. An ideal solution should be [cached](https://github.com/joe-bell/next-placeholder/issues/1#issuecomment-718597748) ideally in a [single JSON file](https://github.com/joe-bell/next-placeholder/issues/1#issuecomment-718745360).
- **Respect configuration** - Any solution **must** respect [image configuration in `next.config.js`](https://nextjs.org/docs/basic-features/image-optimization#configuration) (e.g. domains and loaders).

**Comment by simonireilly** [comment]
This is interesting, I think the main attraction of `_next/image` is for online processing of image formats.

I guess you would need to fetch the entire image from the loader and generate the hash from that as in:

https://github.com/joe-bell/next-blurhash/blob/fd1fd84e87f83a2007f0452bed0b497d1a26612f/packages/next-blurhash/src/index.ts#L22-L31

Since this could be `N` images depending on the `getStaticProps` implementation it will create HTTP bounded build times.

I think caching the output hash against the absolute loader url might be required to optomise build times for these sites and avoid eating up the bandwidth from your image CDN on every build.

What do you think?

**Comment by joe-bell** [comment]
Thanks @simonireilly, sounds sensible to me.

One approach I'm actually using in [joebell.co.uk](https://joebell.co.uk) articles is to build a JSON file of hashes at build time for all images in `public` (e.g. to transform images in Markdown content). It looks something like this:

```json
{
  "/assets/image/2019-01-03--hero-do-not-disturb.jpg": "UgJRXCtSNKo#_NIVxtWB_3RPaea|x]RjWBt6",
  "/assets/image/2020-06-17--bali.jpg": "U9Bp9I^N4-Iq?dofM{WV00Ek-;xZDgo1xvoe",
  "/assets/image/2020-06-17--estonia.jpg": "UfBNW?MvWAof.Aj]WAay%iogaxWAo#t8kCay",
  "/assets/image/2020-06-17--kitchen.jpg": "UQH_fF_4^,?b$_xuogWB_2s.IUM_?HxaM{of",
  "/assets/image/home.jpg": "UxKnrJt7%goz~qa#juofxua|Riayo#ayRjay"
}
```

Perhaps we could cache the hashes in a similar format for all images (remote/local)?

**Comment by pcwa-ahendricks** [comment]
Since getBlurhash() is called within getStaticProps couldn't you use fetch instead of fs.readfile?

**Comment by joe-bell** [comment]
For sure @pcwa-ahendricks 

---

OK I've just updated the issue with some requirements. I'm using local images so this isn't a huge priority for me right now, but I'd be more than happy to support/jump on a call with someone who needs this urgently and wants to pick it up sooner

**Comment by kjbrum** [comment]
@joe-bell I'd love to take a crack at this, would love to be able to use this on projects, but generally use remote images.

Do you have a good example for the JSON caching approach?

**Comment by joe-bell** [comment]
Hey @kjbrum, thanks for your kind offer to pick his up but I'm actually going to suggest putting this specific feature on hold due to https://github.com/vercel/next.js/issues/18858#issuecomment-722963197

Keep your notifications on for this issue though, as things may change. Thanks again!

**Comment by joe-bell** [comment]
Hey again @kjbrum! I've tried chatting to the Next.js folks about this some more but haven't heard any recent developments. Would you still be interested in picking this up? If so, I'd be super grateful!

**Comment by joe-bell** [comment]
Excited to announce that development for this feature has been completed, and it will be available in the [upcoming 2.0 release](https://github.com/joe-bell/plaiceholder/pull/80)

**Comment by joe-bell** [comment]
It's here 🚀

**Comment by jacklimwenjie** [comment]
Sorry, but is there an example of how to use Placeholder with a remote image now?

**Comment by joe-bell** [comment]
@jacklimwenjie hey! Try calling the function with a URL instead of a file path:

```ts
const plaiceholder = await getPlaiceholder("https://some-site.com/path-to-your-image.jpg");
```

Think it's probably worth chucking this in the docs, so thanks for the heads up 🙏

**Comment by jacklimwenjie** [comment]
@joe-bell Thanks for the reply! 

Wow that's really simple 👍 

I am interested to know more what happened in the background when I call the function - does it download the original image and then generate the blurred image placeholder? 

Does this means that if I run this function in the `getServerSideProps` on a Next.js project, the SSR page would take slightly longer time to load without the function?

**Comment by joe-bell** [comment]
@jacklimwenjie just updated the docs to mention the ability of "remote URL" use! (https://github.com/joe-bell/plaiceholder/pull/161)

In answer to how it works, Plaiceholder will download the image and then cache it in memory for future reference. I don't have many metrics on with/without SSR I'm afraid – I think this probably requires some manual testing on your end!
