### ISSUE TITLE
Unsupported file type when url contains "ß" character (and maybe other characters) - Next

### ISSUE THREAD

**Issue by LeeBuckle** [joe-bell/plaiceholder#124]
**Describe the bug**
Sorry if this isn't a bug and I'm just an idiot, unable to figure it out.

I'm using:
**plaiceholder** - **2.0.1** (it looks like there's a 2.1.0 version but it's not on npm, maybe this is my issue)
**@plaiceholder/next** - **2.1.0**
**next** - **11.0.1**
**sharp** - **0.28.3**

I've never used TS before and I'm not using it in this project either, I'm not sure if that could be a problem.

I'm getting a `TypeError: unsupported file type: undefined (file: undefined)` error.

```
// next.config.js
const { withPlaiceholder } = require("@plaiceholder/next")

module.exports = withPlaiceholder({
  images: {
    domains: ['beer-shop-cms.local'],
  }
})
```

```
// [product].js
export async function getStaticProps({ params: { product } }) {
  const props = await client.query({
    query: singleProductQuery,
    variables: { id: product }
  })

  const {base64} = await getPlaiceholder(props.data.product.image.sourceUrl)

  return { props }
}
```

Full error:
```
TypeError: unsupported file type: undefined (file: undefined)
    at lookup (/Users/lee/Web Apps/strapi-shop-test/node_modules/plaiceholder/dist/index.js:4625:11)
    at imageSize (/Users/lee/Web Apps/strapi-shop-test/node_modules/plaiceholder/dist/index.js:4692:14)
    at getImageSize (/Users/lee/Web Apps/strapi-shop-test/node_modules/plaiceholder/dist/index.js:4741:7)
    at loadImage (/Users/lee/Web Apps/strapi-shop-test/node_modules/plaiceholder/dist/index.js:4781:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getImage (/Users/lee/Web Apps/strapi-shop-test/node_modules/plaiceholder/dist/index.js:4851:7)
    at async getPlaiceholder (/Users/lee/Web Apps/strapi-shop-test/node_modules/plaiceholder/dist/index.js:4928:7)
    at async eval (webpack-internal:///./pages/index.js:83:9)
    at async Promise.all (index 0)
```

I tried using this within a map too, using `Promise.all()`. The same thing occurred:

```
// index.js
export async function getStaticProps() {

  // Fetch featured products from WordPress
  const productsObject = await client.query({ query: featuredProductsQuery })
  const products = productsObject.data.products.nodes

  // Create products array with placeholders
  const productsArray = await Promise.all(
    products.map(async (product) => {
      // Generate placeholder from image source
      const { base64 } = await getPlaiceholder(product.image.sourceUrl)

      console.log({
        ...product,
        image: {
          ...product.image,
          placeholder: base64
        }
      })

      return {
        ...product,
        image: {
          ...product.image,
          placeholder: base64
        }
      }
    })
  ).then((values) => values)

  return {
    props: {
      products: productsArray
    }
  }
}
```

As you can see, there's a console log of what I'm trying to return in my map. The output shows that the base64 string has been added to my original objects as intended, but I still get the error.

If it helps, the error shows first, followed by my console logs of the objects.

If I try to console log `productsArray` before my final return, nothing get's output.

Thanks for any help, been struggling with this for hours.

**Expected behavior**
I expect to be able to generate base64 strings without errors.

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Chrome

**Comment by joe-bell** [comment]
Hey @LeeBuckle, thanks for the write up!

As far as I can see there is indeed a [`v2.0.1` on NPM](https://www.npmjs.com/package/plaiceholder/v/2.0.1).   
This error doesn't look like a plaiceholder error to me either (at least it's not an error message I've wrote). 

After a quick Google I found this though -  perhaps it could be the issue you're facing 🤞 
https://stackoverflow.com/questions/68008498/nextjs-typeerror-unsupported-file-type-undefined-after-update-to-v-11

**Comment by LeeBuckle** [comment]
I'm using the latest version of next (11.0.1) and I've tried the canary build.

I've gotten closer to the issue now. It seems to be related to non-english characters in file names, or possibly just the german "ß" character as found in the image I was trying generate base64 for - _Engelszell-Trappisten-Wei**ß**e.jpg_

I thought the error was triggering on all images but it just so happened that in both my single image testing and my testing within a map, the image with the german character was the first image passed the plaiceholder.

Next seems to be able to handle this character fine. Prior to using plaiceholder, using this image url in both a regular `<img/>` tags and `<Image/>` components worked fine.

**Comment by joe-bell** [comment]
Just to reiterate – this is not a plaiceholder error message, it's a Next.js one

Out of curiosity I did however try adding an image with the exact same file name as yours and had no issue…

```tsx
import * as React from "react";
import { InferGetStaticPropsType } from "next";
import Image from "next/image";
import { getPlaiceholder } from "plaiceholder";
import { config } from "@/config";
import { ImageGrid, ImageGridItem } from "@/components/image-grid";
import { Layout } from "@/components/layout";

export const getStaticProps = async () => {
  const { base64, img } = await getPlaiceholder(
    "/Engelszell-Trappisten-Weiße.jpg",
    { size: 10 }
  );

  return {
    props: {
      imageProps: {
        ...img,
        blurDataURL: base64,
      },
      title: config.examples.pages.base64.title,
      heading: config.examples.variants.single.title,
    },
  };
};

const PageBase64Single: React.FC<
  InferGetStaticPropsType<typeof getStaticProps>
> = ({ title, heading, imageProps }) => {
  console.log(imageProps);
  // Logs…
  // {
  //   src: '/Engelszell-Trappisten-Weiße.jpg',
  //   width: 576,
  //   height: 432,
  //   type: 'jpg',
  //   blurDataURL: 'data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAIAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEG/8QAIxAAAgEDAwQDAAAAAAAAAAAAAQIDAAQFBhEhBxUjMUFRYf/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAGREBAAMBAQAAAAAAAAAAAAAAAQACEgOR/9oADAMBAAIRAxEAPwDLaR1Bk8P0/SwkftdrJcNNJdQReaV+AVD+uPz7qyXWFaRmknyBckliyjcn53pSp1+O0Wz7CwT/2Q=='
  // }
  
  return (
    <Layout variant="example" title={title} heading={heading}>
      <ImageGrid columns={2}>
        <ImageGridItem key={imageProps.src}>
          <Image {...imageProps} placeholder="blur" />
        </ImageGridItem>
      </ImageGrid>
    </Layout>
  );
};

export default PageBase64Single;
```

Given the above works, I think this is more likely to be something to do with the encoding of special characters on the Next.js side, but it's difficult to determine without a full reproduction. I suggest you take it up with Next.js folks! (or perhaps consider not using special characters)
