### ISSUE TITLE
error - ./node_modules/plaiceholder/dist/index.esm.js:8:0 Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by jayagrwal** [joe-bell/plaiceholder#131]
**Describe the bug**
Can't resolve 'fs' when trying to import `getPlaiceholder` in a component in Next js

when running `next dev` it throws the above error

  "dependencies": {
    "@plaiceholder/next": "^2.1.0",
    "fs": "0.0.1-security",
    "glob": "^7.1.7",
    "next": "^11.0.1",
    "plaiceholder": "^2.0.1",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-bootstrap": "^1.6.1",
    "react-dom": "^17.0.2",
    "react-hook-form": "^7.8.5",
    "react-icons": "^4.2.0",
    "sharp": "^0.28.3",
  },
  "devDependencies": {
    "@types/node": "^15.14.3",
    "@types/react": "^17.0.9",
    "autoprefixer": "^10.3.1",
  },

**Comment by joe-bell** [comment]
Plaiceholder is a [**Node.js library**](https://plaiceholder.co/docs/usage) — i.e. you can only use within `getStaticProps` or on the server-side
