### ISSUE TITLE
Failed to compile ./node_modules/plaiceholder/dist/index.esm.js:8:0 Module not found: Can't resolve 'fs' null

### ISSUE THREAD

**Issue by krishaamer** [joe-bell/plaiceholder#136]
Hi @joe-bell, thanks for the awesome library! Unfortunately I can't get it to work on Next.js using your examples in the documentation. I read through the previous reports and it seems it can only be used inside a Page and not inside a Component? Thanks.

**Comment by joe-bell** [comment]
Hey @krishaamer! That's correct, Plaiceholder is a Node.js library so it's really only ideal for static or server-side functions (e.g. `getStaticProps`)
