### ISSUE TITLE
Configurable parameters for `getPlaiceholder`

### ISSUE THREAD

**Issue by kruserr** [joe-bell/plaiceholder#171]
I use this library for progressive image rendering in next.js.
I noticed that when the image is upgraded from the placeholder a blinking effect occurs.
Looking at both the images i could clearly see that the placeholder image was brighter than the original image.
This effect is exaggerated with lower amounts of blur filter.
Digging through the source code, i stumbled upon this section.

packages/plaiceholder/src/get-image.ts:157
```js
const getOptimizedForBase64 = pipeline
    .clone()
    .normalise()
    .modulate({ saturation: 1.2, brightness: 1 })
    .removeAlpha()
    .toBuffer({ resolveWithObject: true });
```

Could we perhaps include a `saturation` param for `getPlaiceholder` to allow end users to configure this for their needs?

example
```js
const { base64, img } = await getPlaiceholder(
      'image.jpg',
      { size: 10, saturation: 1 }
);
```

**Comment by kruserr** [comment]
Digging further i found some other config that could also be good to expose to the end user.

Here is what I was thinking for now. Let me know what you think.
```js
const { base64, img } = await getPlaiceholder(
  "https://images.unsplash.com/photo-1621961458348-f013d219b50c?auto=format&fit=crop&w=2850&q=80",
  {
    size: 10,
    saturation: 1,
    brightness: 1,
    normalise: false,
    removeAlpha: false,
  }
);
```

I will do a PR.

**Comment by igordanchenko** [comment]
I want to second this proposal. I ran into an issue with rendering blur image placeholders for PNG images with transparent background. It appears that Plaiceholder generates Base64 GIF image with black background, and unless I'm missing something obvious, there is currently no option to configure this behavior. I put together a quick demo demonstrating this issue - https://qe9in.sse.codesandbox.io

I think one of the following two options would solve my issue:
a) an option to define background color to replace transparent parts of the image
b) generate PNG image with transparent background

**Comment by bwyx** [comment]
any news on this?
i have issue on black opaque on base64 when processing transparent png by plaiceholder, having such a @kruserr's configurable parameters will perfect

**Comment by Evilazio** [comment]
I'm having the same issue when processing transparent png/svg to placeholder, it is generating black background.
Solve this ASAP, please.
