### ISSUE TITLE
Base64 placeholder is generated with a 90 degrees rotation to the left

### ISSUE THREAD

**Issue by SelvinM** [joe-bell/plaiceholder#173]
**Describe the bug**
Base64 placeholder is generated with a 90 degrees rotation to the left. Only happens with images that have a 4x4 dimension. 

**To Reproduce**
1. Get the base64 of an image with a 4x4 dimension (same width as height) by using the getPlaiceholder method. 
2. Display the image to visualize the bug. 

**Expected behavior**
The placeholder shouldn't be rotated

**Screenshots**
Original image:
![image](https://user-images.githubusercontent.com/29130026/142336090-84754fad-ae2d-4edb-ba47-8d00e0c638fb.png)

Blurred image (you can clearly see it's rotated):
![image](https://user-images.githubusercontent.com/29130026/142336030-dc2f8124-347d-4331-ad8b-1b2c4fae4c1c.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version 95.0.4638.69 (Official Build) (64-bit)

**Additional context**
I'm using nextjs 12.0.3 and I'm generating the base64 string inside a graphql resolver function.

**Comment by SelvinM** [comment]
I fixed the problem by using a rotate method to the pipeline. Like so:
`const getOptimizedForBase64 = pipeline
    .clone()
    .normalise()
    .modulate({ saturation: 1.2, brightness: 1 })
    .removeAlpha()
    .rotate()
    .toBuffer({ resolveWithObject: true });`
    
The images I'm using have to be auto-oriented  to the EXIF Orientation tag or else the image appears rotated. This is what adding the rotate() method accomplishes.

**Comment by joe-bell** [comment]
Interesting, thanks for following up – I think it might be still worth adding this feature
