### ISSUE TITLE
"Can't find module "fs"" when importing page from another file

### ISSUE THREAD

**Issue by Pitasi** [joe-bell/plaiceholder#178]
**Describe the bug**

I was able to try plaiceholder using the Next.js example from the docs. However, I usually put my page code in a separate folder (e.g. `src/features/something/MainPage.tsx`) then in my actual Next.js pages folder (`src/pages/index.tsx`) I just have something like this:

```ts
export { default, getStaticProps } from '@/features/something/MainPage';
```

**To Reproduce**

1. Copy the next.js example from https://plaiceholder.co/docs/usage#example in `src/page.tsx`
2. Create a `pages/example.tsx` importing the previous file:
```ts
export { default, getStaticProps } from '../src/page';
```
3. Open the page in browser, or run `yarn build` 
4. Both ways, you get a `Can't finde module fs` error

**Expected behavior**

I'm not sure if my way of separating pages code is "unusual" and if it's worth to fix such a bug. In any case I wanted to report this bug :)

**Additional context**
Full error:
```
wait  - compiling /test...
error - ./node_modules/plaiceholder/dist/index.esm.js:8:0
Module not found: Can't resolve 'fs'

Import trace for requested module:
./src/features/session/components/teststest.tsx
./src/pages/test.tsx

https://nextjs.org/docs/messages/module-not-found
```

**Comment by joe-bell** [comment]
Hey @Pitasi! Sorry to hear you got stuck, funnily enough this is also something I got stuck with when I started with Next.js

From my understanding, Next.js only allows `fs` within `getStaticProps` that are defined in the `/pages` directory.

There are a few old issues open about this (e.g. https://github.com/vercel/next.js/issues/7755). You may be able to adjust your Webpack config to get what you need, but I'm afraid this is probably out of scope for Plaiceholder

Hope you get this resolved 🙏
