### ISSUE TITLE
Extremely slow on local development

### ISSUE THREAD

**Issue by dca123** [joe-bell/plaiceholder#187]
**Describe the bug**
When using plaiceholder to generate base64 images on Next.js, it takes really long to generate page props. My code looks similar to what is recommended in the placiholder docs. I also configured my next.config.js to look like this 
```
const { withPlaiceholder } = require("@plaiceholder/next");

module.exports = withPlaiceholder({
  /** @type {import('next').NextConfig} */
  reactStrictMode: true,
  images: {
    domains: [
      "images.unsplash.com",
      "source.unsplash.com",
      "s3.us-west-2.amazonaws.com",
    ],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
  },
});
```

**To Reproduce**

1. Create Next Page with `getStaticProps`
2. Return img and base64 after waiting for the placeholder
3. Render with Next Image.

**Expected behavior**
Is there a way to cache these images maybe ? My understanding is with Next.js

> [In development (next dev), getStaticProps will be called on every request.
](https://nextjs.org/docs/basic-features/data-fetching/get-static-props#runs-on-every-request-in-development)

**Screenshots**
![image](https://user-images.githubusercontent.com/3579142/151519228-fce4df03-dcd1-4174-8d70-eb1973bbbb82.png)

I'm not sure if this is expected behaviour or I've missed something. If it is expected, would you have any recommendations on how this could be improved ?

**Comment by joe-bell** [comment]
Images [are cached](https://github.com/joe-bell/plaiceholder/blob/main/packages/plaiceholder/src/get-image.ts#L38)! I'm afraid this would need a minimal reproduction to investigate – but even then, there are too many variables here to consider. Sorry, don't think I can offer much help here 🙏
