### ISSUE TITLE
Option to allow custom path when sourcing locally.

### ISSUE THREAD

**Issue by martin2844** [joe-bell/plaiceholder#209]
Currently to source a picture locally we need to include the trailing `/` and that adds a path.join("public", imagePath).
I want to source images from another folder, that does not have public as a parent.
Currently I need to monkey patch this, is there a way we can have an option for a custom local path without public being forced?

**Comment by joe-bell** [comment]
Closing as this doesn't follow the issue template (and as it's a duplicate of #165)
