### ISSUE TITLE
generated images changed from webp to png

### ISSUE THREAD

**Issue by bonesoul** [joe-bell/plaiceholder#219]
After 2.5.0 upgrade, generated placeholder images changed from webp to png.

The release notes mentions the change:

`Up to 30% smaller Base64 placeholders by default (thanks for the recommendation @sebastienbarre)`

And i guess the referred discussion is here: https://github.com/joe-bell/plaiceholder/issues/195

The thing is that after the change my generated images format changed from web to png.

And from my internal testing the same image generates these outputs:

```
BEFORE => (1, 640, 427, 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoEAAMAAUAmJQBOgCHfwHkAAN5n/9t+y/+G+wIZTG5z3+hyYqNlvPf6HJiTH0K9ZffTFwAA'),
(1, 640, 427, AFTER => 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAGklEQVR4nGNgkI9h0K6AIgajegTn0v+3cAQAw1QP94RBOWUAAAAASUVORK5CYII='),
```

Did the change really generates 30% smaller images? From byte count at least, it doesn't seem so.

**Comment by joe-bell** [comment]
Closing as this does not follow the issue template 

Please use the `format` option if you want to specify webp
