### ISSUE TITLE
Using getPlaiceholder makes my nextjs page load significantly slower.

### ISSUE THREAD

**Issue by RisKakaN** [joe-bell/plaiceholder#228]
**Describe the bug**
I have a page that should load cards (in this case, about 5 cards) where each card contains an image and some text. The content and image url is loaded from my firebase database, pretty quick without issues. But once I make use of getPlaiceholder, and use the returned base64 and img source, the loading time of my page takes a lot longer.

So I am wondering, is this slow loading time expected, or am I using it incorrectly?

**To Reproduce**
I am testing on my local environment, with nextjs 13, and firebase firestore.

1. My page loads.
2. This page is async, so it will await for my database content to be loaded until the ui cards are displayed.
3. When I use getPlaiceholder, I am adding it as another await, chained after my database content has loaded. So once getPlaiceholder is finished, then my cards will display.
4. I am using nextjs image to display the image source and base64

Here is the api call followed by generating base64.
Basically, I fetch my database data, which contains some text and an image URL. So I get a list of data items.
Once that is finished, I call getPlaiceholder for every item, and generate the base64 and image source. And just add the image and base64 to the data list.
Then finally, the UI is rendered. (This is a nextjs 13 async server side page, so it will fetch the data before loading the cards)
```
 const recipeDocuments = (
        await adminFirestore
            .collection("userContent")
            .doc(user.id)
            .collection("recipes")
            .get()
    ).docs;

    const recipeList: RecipeListCard[] = await Promise.all(
        recipeDocuments.map(async (recipeDocument) => {
            const recipe: Recipe = recipeDocument.data() as Recipe;
            const recipeListCard: RecipeListCard = {
                ...recipe,
                recipeId: recipeDocument.id,
            };
            if (recipe.image != null) {
                const { img, base64 } = await getPlaiceholder(recipe.image.url);
                console.log(base64);
                recipeListCard.image = {
                    ...recipe.image,
                    url: img.src,
                    blurData: base64,
                };
            }
            return recipeListCard;
        })
    );
```

Then the list of data will be rendered, where each item contains this Image:
```
<Image
        src={plaiceholderData?.img.src}
        alt="Recipe image"
        fill={true}
        sizes="100vw, 100vw, 100vw"
        placeholder={plaiceholderData != null ? "blur" : undefined}
        blurDataURL={plaiceholderData?.base64}
/>
```

If I use a static base64 (just copying a previously generated one), there is no slowness. So it is when getPlaiceholder is run, that will slow it down.

**Expected behavior**
I do not expect getPlaiceholder to take so long time. It takes at least double the amount of time, as without using getPlaiceholder.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 110.0.5481.177

**Smartphone (please complete the following information):**

**Additional context**
A side question:
If all this loading time is expected, I am wondering, is there a utility where I can generate a base64 from either of the following:
- On client side (currently I can only call getPlaiceholder in nodejs)
- Use getPlaiceholder but with an actual image file or a base64 image, instead of a url to the image?

Because then I can save the plaiceholder base64 in my database, and do not need to the the generation on the fly, thus saving loading time.
And reason why I need to either call this function on client, is because that is where I will have the temporary URL in the browser.  (not sure if this actually works though, since it is not a remote url in the same sense).
And reason for having getPlaiceholder take in a base64 image, is because I have the full image as a base64 already, for saving it to my image storage.

Thanks for any help!

**Comment by joe-bell** [comment]
Could you instead try downloading the image prior, convert to a buffer, and then pass to `getPlaiceholder`? 

This will help me determine the root of the issue; I suspect it's the fetch that's the slowness here

**Comment by RisKakaN** [comment]
I tested the following two scenarios, where I skip my api data fetch completely, by mocking identical data, which includes the images as URLs.

Scenario 1: Instead of an image URL, I will replace it with Buffers as you said. i read my locally saved images, turn them into buffers, and pass into getPlaiceholder. and the return value of img is null. so in my nextjs Image, I have to use the original image url as the source.
The result is that this does not seem to be as slow as before. and more desirable. but i would not want to store my images as buffers. they are stored as remote image urls.

Scenario 2: Just pass in the mocked data, that contains the original image URLs.
The getPlaiceholder is still slow. Not much difference from when I used my real data fetch.

is the slowness due to getPlaiceholder using a remote URL, and doing something extra?
since the whole chain is async await, i assume getPlaiceholder is doing its thing and completes it fully before my page content gets rendered. but ideally, i would want it to give the blurred image as quickly as possible. instead, there seems to be some waiting time, which maybe is the loading of the full remote image. and since i await the whole function getPlaiceholder, it will wait for everything. maybe this is how it has to work, because you cant generate a base64 blur without loading the full image. but if that is the case, i feel like it defeats the purpose. because i thought the function would give you a low res blur image almost instantly so that i can render it as a placeholder, until the function gives back the full image.


in any case, my ideal scenario would be to have a utility that can convert a full base64 image into a blurred version base64, which I can store in my database directly when I save images. then when i render my list of cards, i would not need to call getPlaiceholder on the fly, which adds extra waiting time. i could then just load the low res blurred base64 in my nextjs image.

for example:
`const verySmallBase64Image = getPlaiceholder(fullBase64Image)`

are you aware of any utility that could do such a thing?

Thanks for the help!

**Comment by eug-vs** [comment]
Hey @RisKakaN I think you are missing something, if I understand your problem correctly. The catch is: placeholder generation, as you pointed out, is *async* and takes some time to generate. So you will inevitably notice slower response if you generate placeholder *every time your recipe document is fetched*. So you should avoid generating placeholder at request time, and instead generate it *every time when your actual image changes*, storing it in the database along with everything else. 

This way, in your particular case, the request flow will look like this:
1. data is fetched from remote database
2. nextjs uses `src` and *pre-computed* `blurDataURL` to build an HTML for your `<img>` and render it on the server
3. client receives valid html and the rest is the job for the browser

Notice how `plaiceholder` doesn't run anywhere in these steps (hence no extra time spent `await`ing). And then you just choose when to generate your `blurDataURL` - e.g you can do it asynchronously in the background after user creates a new recipe.|

P.S Actually now reading your last sentences I think you already figured it out, but hopefully this helps anyway.

**Comment by eug-vs** [comment]
> utility that can convert a full base64 image into a blurred version base64

Just store whatever base64 `plaiceholder` returns (it's relatively small by definition). NextJS `Image` component will handle everything else itself when you pass the `blurDataURL={base64}` prop

**Comment by RisKakaN** [comment]
Thanks for the answers!
Yes that’s the plan.

However, the one issue I have is that:
I have an image in base64 format.
I would like getPlaiceholder to take in a base64, not a path to the image.

Like this:
const verySmallBase64Image = getPlaiceholder(fullBase64Image)

Because I will save this on the backend, and I do not have access to the path to the image.
Storing an image temporarily is not an option for me.
I would like to solve this by going from full base64, to the small blur version.

**Comment by eug-vs** [comment]
Ah that's what I missed. Not sure if it's possible in the current version of the library, I guess here you can remove a call to `loadImage` (that performs `fetch`) and just pass your base64 as a buffer to `optimizeImage`

**Comment by eug-vs** [comment]
I'm not the maintainer of this library, so I have no idea about plans. Forking is fine, you could even request to merge this functionality back here later, if the maintainers are good with it.

**Comment by RisKakaN** [comment]
Thanks! I will explore the different solutions and see what I will do.
