### ISSUE TITLE
Images with a clear background (PNG).

### ISSUE THREAD

**Issue by z0lo13** [joe-bell/plaiceholder#39]
**Is your feature request related to a problem? Please describe.**

The current approach create a blurred image and places it under the actual image. Because of the placeholder is still displayed even after the actual image is loaded, it creates a blur effect for an actual image. Maybe it looks good for the fish on homepage, however it absolutely unusable for a complex illustrations, and also this style does not fit every web design.

**Describe the solution you'd like**
Listener which hide the placeholder as soon as image is loaded.

**Comment by joe-bell** [comment]
Hey @z0lo13, thanks for taking the time to write this up!

Whilst I understand your concerns, I think this feature request is out of the project's scope. If we were to add components/listeners for individual frameworks, this would become difficult to maintain. I'd rather keep this project's core focus on the "transformation" (server/statically-generated)

**Comment by sebqq** [comment]
@joe-bell maybe it would be nice to also include [image-trace](https://www.npmjs.com/package/image-trace-loader) processing as an option. Using that loader, even semi-transparent images can get a nice placeholder, which doesn't "overflow" over real image.

By the way, how do you feel about some kind of "How to write custom image transformation plugin" guide?

And thanks for this lib! It's really great.
