### ISSUE TITLE
Next.js builds locally, but not on Vercel (next@10.0.9)

### ISSUE THREAD

**Issue by HyBDev** [joe-bell/plaiceholder#60]
Hi!

**Describe the bug**
I try to use Plaiceholder on a Next app and I followed the instructions to do it and it works fine... but only when I build locally.
When I try to build on the vercel server, I've a SIGSEGV exit error.

**Screenshots**
Build on vercel server
![image](https://user-images.githubusercontent.com/26486143/112560331-5e89a300-8da9-11eb-8ea2-05d27a6eb2f1.png)

Build on local
![image](https://user-images.githubusercontent.com/26486143/112560396-7c570800-8da9-11eb-9ec8-7b6740fed113.png)

**Comment by joe-bell** [comment]
Thanks! Before I can look into this, I'll need a minimum reproduction/codesandbox. It's difficult to get an idea of the issue without seeing the full context

**Comment by LBRDan** [comment]
Hello there
Stumbled onto this just about last night
The Vercel Support came back to me this morning, claiming a problem about a failed native deps installation for plaiceholder/core package `sharp`. Their suggestion is to switch to a pure js library, but i don't think there are any alternatives  in this field.

Btw, i tried on Netlify and i'm getting a similar outcome (errcode 139) when the build enters the same optimization step

I believe that maybe this issue should be reflected back to lovell/sharp but there are tons of issues about various serverless envs (mainly AWS based)

https://github.com/lovell/sharp/issues/2499
https://github.com/lovell/sharp/issues/1875

Dropping a rough one: Are there alternatives pure js alternatives to `sharp` on reading raw pixels buffer arrays?

**Comment by joe-bell** [comment]
Thanks for the details @LBRDan!

I spent some time looking around for JS alternatives this morning, but it's going to be a bit of work to build/test this out.

I'm not super convinced it's a good idea to start refactoring things until I'm 100% sure this isn't an upstream issue–because this works perfectly fine for all Next.js versions prior to 10.0.9 (as well as 11ty)

**Comment by joe-bell** [comment]
@HyBDev @LBRDan please can you both confirm what versions of Next.js you're using

**Comment by HyBDev** [comment]
I'm using the 10.0.9 and I plan to try with the 10.0.3 today. I will also try some other things to investigate a bit more on that.

**Comment by LBRDan** [comment]
I'm on 10.0.9 
I'll try to lock some others 10.0.x in a few hours and let you know

**Comment by HyBDev** [comment]
Okay, I confirm it works for me with the 10.0.3 Next version.

**Comment by joe-bell** [comment]
Tried this with the beta version of `sharp` but still no luck. I've contacted Vercel support to see if we can look into this

**Comment by joe-bell** [comment]
I've managed to create a reproduction of this issue, and I've raised a bug on the Next.js repo:
https://github.com/vercel/next.js/issues/23531

**Comment by joe-bell** [comment]
**Update:** [**@​lovell** kindly took the time to investigate, and offered a fix](https://github.com/lovell/sharp/issues/2655#issuecomment-815684743) 🎉 

Add `require('sharp')` to your `next.config.js`:

```js
// next.config.js
require('sharp');
module.exports = {};
```

For more background see https://github.com/lovell/sharp/issues/2655#issuecomment-815684743

---

I'm going to check with the Next.js team [if this is recommended](https://github.com/vercel/next.js/issues/23531#issuecomment-815690755) before I update the docs, but for now this should offer a quick fix

**Comment by joe-bell** [comment]
Docs/Examples updated in #81

**Comment by joe-bell** [comment]
The new [`@plaiceholder/next`](https://plaiceholder.co/docs/plugins/next) package resolves this!

**Comment by perenstrom** [comment]
@joe-bell, I'm still getting the same errors when depoying to Vercel. Sharp cannot be found (see log: https://pastebin.com/zTzaWdpT). And I've added the wrapper around my next config (https://github.com/perenstrom/maria-petersen-enstrom/blob/main/next.config.js). Any idea what's behind this?

**Comment by joe-bell** [comment]
@perenstrom hello! Looks like you need to [add `sharp` to your dependencies](https://plaiceholder.co/docs/usage#prerequisites)
