### ISSUE TITLE
Doesn't look perfect when using `object-fit: cover` on image element

### ISSUE THREAD

**Issue by baptisteArno** [joe-bell/plaiceholder#85]
**Is your feature request related to a problem? Please describe.**
When using `object-fit: cover` CSS prop, then the placeholder looks off.

**Describe the solution you'd like**
I'm not sure how we can do this clearly, maybe there is a workaround?

**Comment by joe-bell** [comment]
If `object-fit` is of concern then I wouldn't recommend using `CSS`, use a [Base64](https://plaiceholder.co/docs/strategies#base64) image instead:

```jsx
import { getBase64 } from "@plaiceholder/base64";

export async function getStaticProps() {
  const src = '/path-to-image';
  const base64 = await getBase64(src);

  return {
    props: {
      src,
      base64,
    }
  }
}

function Page({ src, base64 }) {
  return (
    <div style={{...containerStyles}}>
      <img aria-hidden="true" alt="" src={base64} style={{...placeholderStyles, ...objectFitStyles}} />
      <img alt="Some appropriate alt text" src={src} style={{...objectFitStyles}} />
    </div>
  )
}

export default Page;
```

---

This is a good shout though, thanks for bringing up! I'll make sure to include in the new docs for #80
